# Generated by Django 5.1.4 on 2026-03-05 07:43

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Name shown on the map and in search results.",
                        max_length=150,
                        verbose_name="display name",
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Short description visible to nearby users.",
                        max_length=500,
                        verbose_name="bio",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, null=True, upload_to="avatars/%Y/%m/", verbose_name="avatar"
                    ),
                ),
                (
                    "skills",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        help_text="List of skills this user offers (e.g., 'plumbing', 'tutoring').",
                        size=None,
                    ),
                ),
                (
                    "interests",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        help_text="List of interests or needs (e.g., 'food assistance', 'legal aid').",
                        size=None,
                    ),
                ),
                (
                    "tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        default=list,
                        help_text="AI-generated or user-set tags for matching (e.g., 'Food', 'Shelter', 'Electrician').",
                        size=None,
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Public profiles (businesses/NGOs) show exact GPS on the map. Private profiles (individuals) show an obfuscated location only.",
                        verbose_name="public profile",
                    ),
                ),
                (
                    "live_tracking_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="When enabled, the app may update location in the background. A persistent OS notification is required when active.",
                        verbose_name="live tracking enabled",
                    ),
                ),
                ("is_online", models.BooleanField(default=False, verbose_name="currently online")),
                (
                    "last_seen",
                    models.DateTimeField(blank=True, null=True, verbose_name="last seen"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "profile",
                "verbose_name_plural": "profiles",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["is_public"], name="idx_profile_is_public"),
                    models.Index(fields=["is_online"], name="idx_profile_is_online"),
                ],
            },
        ),
    ]
