# Generated by Django 5.1.4 on 2026-03-05 07:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Block",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True, default="", max_length=500, verbose_name="reason"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "blocked",
                    models.ForeignKey(
                        help_text="The user who has been blocked.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "blocker",
                    models.ForeignKey(
                        help_text="The user who initiated the block.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "block",
                "verbose_name_plural": "blocks",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["blocker"], name="idx_block_blocker"),
                    models.Index(fields=["blocked"], name="idx_block_blocked"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("blocker", "blocked"), name="unique_block_pair"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("blocker", models.F("blocked")), _negated=True),
                        name="no_self_block",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("profile", "User Profile"),
                            ("status", "Status / Broadcast"),
                            ("chat_message", "Chat Message"),
                        ],
                        max_length=20,
                        verbose_name="content type",
                    ),
                ),
                (
                    "content_id",
                    models.UUIDField(
                        blank=True,
                        help_text="UUID of the reported content (status ID, message ID, etc.). Null if the report is against the user's profile in general.",
                        null=True,
                        verbose_name="content ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("spam", "Spam"),
                            ("harassment", "Harassment / Bullying"),
                            ("hate_speech", "Hate Speech"),
                            ("inappropriate", "Inappropriate Content"),
                            ("impersonation", "Impersonation"),
                            ("scam", "Scam / Fraud"),
                            ("violence", "Violence / Threats"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        verbose_name="category",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional additional details from the reporter.",
                        max_length=1000,
                        verbose_name="description",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("reviewing", "Under Review"),
                            ("resolved", "Resolved"),
                            ("dismissed", "Dismissed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="review status",
                    ),
                ),
                (
                    "moderator_notes",
                    models.TextField(blank=True, default="", verbose_name="moderator notes"),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="resolved at"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reported_user",
                    models.ForeignKey(
                        help_text="The user being reported.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        help_text="The user filing the report.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports_filed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports_resolved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "report",
                "verbose_name_plural": "reports",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"], name="idx_report_status_created"
                    ),
                    models.Index(fields=["reported_user"], name="idx_report_reported_user"),
                ],
            },
        ),
    ]
