# Generated by Django 5.1.4 on 2026-03-05 13:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("statuses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataIngestionJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "source_name",
                    models.CharField(
                        help_text="Name or identifier of the data source.",
                        max_length=255,
                        verbose_name="data source",
                    ),
                ),
                (
                    "job_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=15,
                        verbose_name="status",
                    ),
                ),
                ("total_records", models.PositiveIntegerField(default=0)),
                ("processed_records", models.PositiveIntegerField(default=0)),
                ("failed_records", models.PositiveIntegerField(default=0)),
                ("error_log", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "initiated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ingestion_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "data ingestion job",
                "verbose_name_plural": "data ingestion jobs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AIMatchResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "score",
                    models.FloatField(
                        default=0.0,
                        help_text="AI confidence score (0.0 to 1.0).",
                        verbose_name="match score",
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="AI-generated explanation for this match.",
                        verbose_name="match reason",
                    ),
                ),
                (
                    "matched_tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Tags that overlapped between the status and matched profile.",
                        verbose_name="matched tags",
                    ),
                ),
                (
                    "distance_meters",
                    models.FloatField(
                        blank=True,
                        help_text="Distance between the status location and matched user.",
                        null=True,
                        verbose_name="distance in meters",
                    ),
                ),
                (
                    "match_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("notified", "Notified"),
                            ("viewed", "Viewed"),
                            ("connected", "Connected"),
                            ("dismissed", "Dismissed"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=15,
                        verbose_name="match status",
                    ),
                ),
                ("notified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "matched_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_matches_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="statuses.status",
                    ),
                ),
                (
                    "status_owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_matches_initiated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI match result",
                "verbose_name_plural": "AI match results",
                "ordering": ["-score", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status_owner", "match_status"], name="idx_match_owner_status"
                    ),
                    models.Index(
                        fields=["matched_user", "match_status"], name="idx_match_user_status"
                    ),
                    models.Index(fields=["score"], name="idx_match_score"),
                ],
                "unique_together": {("status", "matched_user")},
            },
        ),
    ]
