# Generated by Django 5.1.4 on 2026-03-05 07:43

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status_type",
                    models.CharField(
                        choices=[("need", "Need / Request"), ("offer", "Offer / Service")],
                        db_index=True,
                        max_length=10,
                        verbose_name="type",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="Describe your need or offer. The AI agent will parse this.",
                        max_length=500,
                        verbose_name="status text",
                    ),
                ),
                (
                    "urgency",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("emergency", "Emergency"),
                        ],
                        default="medium",
                        max_length=15,
                        verbose_name="urgency level",
                    ),
                ),
                (
                    "ai_parsed_intent",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="AI agent's interpretation of the user's intent.",
                        verbose_name="AI parsed intent",
                    ),
                ),
                (
                    "ai_tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Tags extracted by the AI agent (e.g., ['food', 'shelter']).",
                        verbose_name="AI tags",
                    ),
                ),
                (
                    "location_snapshot",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True,
                        geography=True,
                        help_text="Obfuscated point for private users; exact point for public entities.",
                        null=True,
                        srid=4326,
                        verbose_name="location at time of posting",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Inactive statuses are no longer visible or matched.",
                        verbose_name="active",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Auto-deactivate after this time.",
                        null=True,
                        verbose_name="expires at",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statuses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "status",
                "verbose_name_plural": "statuses",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "status_type"], name="idx_status_active_type"
                    ),
                    models.Index(fields=["user", "is_active"], name="idx_status_user_active"),
                ],
            },
        ),
    ]
