# Generated by Django 5.1.4 on 2026-03-05 07:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatRoom",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "participants",
                    models.ManyToManyField(related_name="chat_rooms", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "verbose_name": "chat room",
                "verbose_name_plural": "chat rooms",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ConnectionRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional message sent with the connection request.",
                        max_length=300,
                        verbose_name="intro message",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=15,
                        verbose_name="status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chat_room",
                    models.ForeignKey(
                        blank=True,
                        help_text="ChatRoom created when the request is accepted.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="connection_request",
                        to="chat.chatroom",
                    ),
                ),
                (
                    "from_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connection_requests_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connection_requests_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "connection request",
                "verbose_name_plural": "connection requests",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("from_user", "to_user"), name="unique_connection_request"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("from_user", models.F("to_user")), _negated=True),
                        name="no_self_connection",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("location", "Location Share"),
                            ("image", "Image"),
                            ("system", "System Message"),
                        ],
                        default="text",
                        max_length=15,
                        verbose_name="type",
                    ),
                ),
                ("content", models.TextField(max_length=2000, verbose_name="content")),
                ("is_read", models.BooleanField(default=False, verbose_name="read")),
                ("read_at", models.DateTimeField(blank=True, null=True, verbose_name="read at")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chat.chatroom",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "message",
                "verbose_name_plural": "messages",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(fields=["room", "created_at"], name="idx_msg_room_created")
                ],
            },
        ),
    ]
