# Generated by Django 5.1.4 on 2026-03-05 07:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("connection_request", "Connection Request"),
                            ("connection_accepted", "Connection Accepted"),
                            ("connection_declined", "Connection Declined"),
                            ("new_message", "New Message"),
                            ("ai_match", "AI Match"),
                            ("system", "System"),
                        ],
                        max_length=25,
                        verbose_name="type",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                (
                    "body",
                    models.TextField(blank=True, default="", max_length=500, verbose_name="body"),
                ),
                (
                    "data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON payload with IDs, links, etc. for the client.",
                        verbose_name="extra data",
                    ),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="read")),
                ("read_at", models.DateTimeField(blank=True, null=True, verbose_name="read at")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who receives this notification.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "notification",
                "verbose_name_plural": "notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user", "-created_at"], name="idx_notif_user_created"),
                    models.Index(fields=["user", "is_read"], name="idx_notif_user_unread"),
                ],
            },
        ),
    ]
