# Generated by Django 5.1.4 on 2026-03-05 07:43

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LocationHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "point",
                    django.contrib.gis.db.models.fields.PointField(
                        geography=True,
                        help_text="For private profiles this is the OBFUSCATED point. For public entities this is the exact point.",
                        srid=4326,
                        verbose_name="recorded location",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("gps", "Device GPS"),
                            ("manual", "Manual Entry"),
                            ("network", "Network/WiFi"),
                            ("background", "Background Tracking"),
                        ],
                        default="gps",
                        max_length=20,
                    ),
                ),
                ("recorded_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "location history",
                "verbose_name_plural": "location histories",
                "ordering": ["-recorded_at"],
                "indexes": [
                    models.Index(fields=["user", "recorded_at"], name="idx_lochistory_user_time")
                ],
            },
        ),
        migrations.CreateModel(
            name="UserLocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "point",
                    django.contrib.gis.db.models.fields.PointField(
                        geography=True,
                        help_text="The user's real GPS position. NEVER exposed publicly for private/individual profiles.",
                        srid=4326,
                        verbose_name="exact location",
                    ),
                ),
                (
                    "obfuscated_point",
                    django.contrib.gis.db.models.fields.PointField(
                        geography=True,
                        help_text="Randomized offset position served on the public map for private profiles. Equals exact point for public entities.",
                        srid=4326,
                        verbose_name="obfuscated location",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("gps", "Device GPS"),
                            ("manual", "Manual Entry"),
                            ("network", "Network/WiFi"),
                            ("background", "Background Tracking"),
                        ],
                        default="gps",
                        max_length=20,
                        verbose_name="location source",
                    ),
                ),
                (
                    "accuracy_meters",
                    models.FloatField(
                        blank=True,
                        help_text="GPS accuracy reported by the device.",
                        null=True,
                        verbose_name="accuracy (meters)",
                    ),
                ),
                (
                    "altitude",
                    models.FloatField(blank=True, null=True, verbose_name="altitude (meters)"),
                ),
                (
                    "heading",
                    models.FloatField(blank=True, null=True, verbose_name="heading (degrees)"),
                ),
                ("speed", models.FloatField(blank=True, null=True, verbose_name="speed (m/s)")),
                (
                    "is_background_tracking",
                    models.BooleanField(default=False, verbose_name="background tracking active"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "user location",
                "verbose_name_plural": "user locations",
                "indexes": [models.Index(fields=["updated_at"], name="idx_location_updated")],
            },
        ),
    ]
